### ISSUE TITLE
Refactor into proper package

### ISSUE THREAD

**Issue by stephantul** [stephantul/humumls#5]
We would like to refactor Humumls into a proper package, with e.g. top-level folders. This is underway in the `package` branch. @slimaneadz, do you want to take a look and see if you agree before I do the merge? This will break compatibility with previous releases (not for code reasons, obviously, but because of the change in structure).

**Comment by amiarSlimane** [comment]
yes i do agree , it's a nice idea

**Comment by stephantul** [comment]
This is done
